### ISSUE TITLE
This example is BROKEN - please archive

### ISSUE THREAD

**Issue by julie-ng** [Azure-Samples/vue-cosmosdb#13]
### Problem

Project dependencies are incredibly outdated. `npm install` does not even work. A binary is missing.

/cc @dend @bnb - let's remove outdated examples please :)

See log below.

### Steps to Reproduce

1. `git clone`
2. `npm install` and 🤦‍♂️

### Possible mitigation

1. Delete `package-lock.json`
2. Run `npm update`

But vulnerabilities etc, remain:

```
added 74 packages from 110 contributors, removed 1 package and audited 11100 packages in 11.072s
found 477 vulnerabilities (156 low, 5 moderate, 316 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

### Failed Install Logs

```
vue-cosmosdb master via ⬢ v10.12.0 on 🐳 v19.03.1 took 20s
❯ npm i

> node-sass@4.7.2 install /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.7.2 postinstall /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/10.12.0/bin/node /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/Cellar/node/10.12.0/bin/node',
gyp verb cli   '/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.12.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.15\n"
gyp verb get node dir no --target version specified, falling back to host node version: 10.12.0
gyp verb command install [ '10.12.0' ]
gyp verb install input version string "10.12.0"
gyp verb install installing version: 10.12.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.12.0
gyp verb build dir attempting to create "build" dir: /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/julieng/.node-gyp/10.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/julieng/.node-gyp/10.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/julieng/.node-gyp/10.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/10.12.0/bin/node" "/Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/julieng/Projects/microsoft/vue-cosmosdb/node_modules/node-sass
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN vue-cosmosdb@1.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/julieng/.npm/_logs/2019-08-05T17_29_12_565Z-debug.log
```

**Comment by julie-ng** [comment]
Btw, even after updating the dependencies, the demo is broken - it cannot actually save any "heroes" - beyond the first one 🤔

<img width="981" alt="Screen Shot 2019-08-05 at 21 36 51" src="https://user-images.githubusercontent.com/1269507/62490268-3bbc0c80-b7c9-11e9-847f-0708e35d0f7b.png">
