### ISSUE TITLE
Error when npm run dev-proxy

### ISSUE THREAD

**Issue by ArielZhang** [Azure-Samples/vue-cosmosdb#4]
Branch connect2017

> vue-cosmosdb@1.0.0 dev-proxy /Users/arielzhang/bitbucket/vue-cosmosdb-connect2017
> concurrently "NODE_ENV=development SERVER_PORT=3001 npm start" "npm run dev"

[0]
[0] > vue-cosmosdb@1.0.0 start /Users/arielzhang/bitbucket/vue-cosmosdb-connect2017
[0] > node index.js
[0]
[1]
[1] > vue-cosmosdb@1.0.0 dev /Users/arielzhang/bitbucket/vue-cosmosdb-connect2017
[1] > cross-env NODE_ENV=development webpack-dev-server --open --hot
[1]
[0] module.js:472
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module './server/env/development'
[0]     at Function.Module._resolveFilename (module.js:470:15)
[0]     at Function.Module._load (module.js:418:25)
[0]     at Module.require (module.js:498:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/Users/arielzhang/bitbucket/vue-cosmosdb-connect2017/index.js:5:13)
[0]     at Module._compile (module.js:571:32)
[0]     at Object.Module._extensions..js (module.js:580:10)
[0]     at Module.load (module.js:488:32)
[0]     at tryModuleLoad (module.js:447:12)
[0]     at Function.Module._load (module.js:439:3)
[0]
[0] npm
[0]  ERR! Darwin 16.7.0
[0] npm ERR! argv "/usr/local/Cellar/node/7.7.4/bin/node" "/usr/local/bin/npm" "start"
[0] npm ERR! node v7.7.4
[0] npm ERR! npm  v4.1.2
[0] npm ERR! code
[0]  ELIFECYCLE
[0] npm ERR! vue-cosmosdb@1.0.0 start: `node index.js`
[0] npm
[0] ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the vue-cosmosdb@1.0.0 start script 'node index.js'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the vue-cosmosdb package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!
[0]      node index.js
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs vue-cosmosdb
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm
[0] ERR!     npm owner ls vue-cosmosdb
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     /Users/arielzhang/bitbucket/vue-cosmosdb-connect2017/npm-debug.log
[0] NODE_ENV=development SERVER_PORT=3001 npm start exited with code 1
[1] Project is running at http://localhost:8081/
[1] webpack output is served from /server/www/
[1] 404s will fallback to /index.html
[1] [HPM] Error occurred while trying to proxy request /api/heroes from localhost:8081 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by johnpapa** [comment]
thanks for reporting. i updated the readme to explain how to get the development mode to work with your db keys.
